import { storage, getSettings } from './storage.js';
import { setupRouter, navigate } from './router.js';
import { escapeHTML as e, icon, showToast, showModal, closeModal, refreshIcons, loadScript, formatDuration } from './ui.js';
import { loadDefaultScenario, importScenario, validateScenario } from './scenario-loader.js';
import { createState, saveState, resetSimulation, processAdvisorMessage, fieldLabels, getMissingFields, calculatePackageScores, selectPackage, handleCall, returnCall, addMessage, nextQuestion, checkAutomaticEvents, updateProgress, normalize } from './simulator.js';
import { evaluateSimulation, categoryLabels, scoreLabel } from './evaluator.js';
import { downloadReport } from './report.js';
import { ensureQuestionnaire, questionnaireView, storeFormStep, validateStep, generateFromForm, selectFormPackage } from './questionnaire.js';
let base,scenario,state,settings=getSettings(),route='inicio',selectedResult=null,importDraft=null;
const main=document.querySelector('#main');
const history=()=>storage.get('results',[]);
const scenarios=()=>[base,...storage.get('scenarios',[])];
const button=(label,action,style='primary',extra='')=>`<button class="button ${style}" data-action="${action}" ${extra}>${label}</button>`;
const heading=(title,subtitle,actions='')=>`<div class="page-heading row between"><div><div class="eyebrow">Tu espacio de aprendizaje</div><h1>${e(title)}</h1><p>${e(subtitle)}</p></div>${actions}</div>`;
const empty=(title,text,action='')=>`<section class="empty card"><h2>${e(title)}</h2><p>${e(text)}</p>${action}</section>`;
const active=()=>state&&!state.endTime;
const requireState=()=>state?true:(showToast('Comience un caso desde Escenarios.','info'),navigate('escenarios'),false);
function render(next=route){
 if(next!==route)window.scrollTo({top:0,behavior:'instant'});
 route=next;const labels={inicio:'Inicio',escenarios:'Escenarios',simulacion:'Simulación',paquetes:'Recomendación',reserva:'Reserva',evaluacion:'Evaluación',reportes:'Reportes',configuracion:'Configuración'};
 document.querySelector('#route-label').textContent=labels[route];document.querySelector('#mode-label').textContent=settings.demoMode?'Modo demostración':'Modo práctica';
 document.querySelectorAll('nav a').forEach(a=>{const current=a.dataset.route===route||['paquetes','reserva'].includes(route)&&a.dataset.route==='simulacion';a.classList.toggle('active',current);if(current)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 const views={inicio:homeView,escenarios:scenariosView,simulacion:simulationView,paquetes:packagesView,reserva:reservationView,evaluacion:evaluationView,reportes:reportsView,configuracion:settingsView};
 try{main.innerHTML=views[route]();refreshIcons();if(route==='simulacion'||(route==='paquetes'&&state?.questionnaire)){scrollChat();if(state?.callPending)callModal();}if(route==='reserva')attachReservation();}
 catch(error){console.error(error);main.innerHTML=empty('No fue posible mostrar esta pantalla.','El progreso guardado se conserva. Vuelva al inicio para continuar.', '<a class="button" href="#inicio">Volver al inicio</a>');}
}
function homeView(){
 const results=history();const avg=results.length?Math.round(results.reduce((s,r)=>s+r.totalScore,0)/results.length):'—';
 return `${heading('Cada viaje comienza con tus respuestas.','Practica una atención cercana, inclusiva y memorable.')}
 <div class="stats"><div class="stat"><div class="stat-icon">${icon('flag')}</div><div><strong>${results.length}</strong><span>Simulaciones completadas</span></div></div><div class="stat"><div class="stat-icon">${icon('chart-no-axes-combined')}</div><div><strong>${avg}${results.length?'<small class="small"> / 100</small>':''}</strong><span>Puntaje promedio</span></div></div><div class="stat"><div class="stat-icon">${icon('compass')}</div><div><strong>${scenarios().length}</strong><span>Escenarios disponibles</span></div></div></div>
 <div class="grid-two"><section class="card feature"><div class="feature-banner"><div class="eyebrow">Escenario destacado · 01</div><h2>Destino Centroamérica</h2><p>Una familia, diferentes necesidades.<br>Una experiencia que empieza contigo.</p><span class="badge">Atención presencial</span> <span class="badge">Intermedio</span></div><div class="feature-body"><div class="meta-grid"><div><small>DURACIÓN ESTIMADA</small><strong>15–20 minutos</strong></div><div><small>TU ROL</small><strong>Asesor de viajes</strong></div><div><small>RECORRIDO</small><strong>5 pasos del formulario</strong></div></div><div class="feature-bottom"><span class="small muted">Completa. Elige. Planifica.</span>${button(active()?'Continuar simulación →':'Iniciar simulación →',active()?'resume':'details')}</div></div></section>
 <section class="card"><div class="eyebrow">Aprender en la práctica</div><h2>Así será tu experiencia</h2><ol class="journey"><li><span class="number">01</span><div><strong>Conoce el caso</strong><small>Un contexto, un cliente y un objetivo.</small></div></li><li><span class="number">02</span><div><strong>Completa el cuestionario</strong><small>Indica los datos y preferencias del viaje.</small></div></li><li><span class="number">03</span><div><strong>Propón una experiencia</strong><small>Obtén propuestas según tus respuestas.</small></div></li><li><span class="number">04</span><div><strong>Reflexiona y mejora</strong><small>Recibe retroalimentación de tu atención.</small></div></li></ol></section></div>
 <div class="section-title"><h2 style="margin:0">Tu actividad reciente</h2><a href="#reportes">Ver reportes →</a></div>${results.length?`<section class="card">${resultRows(results.slice(-2).reverse())}</section>`:`<section class="card empty-history"><div class="stat-icon">${icon('notebook-pen')}</div><div><h3>Tu próximo aprendizaje comienza aquí</h3><p>Al completar un caso, encontrarás aquí tus resultados y avances.</p></div></section>`}`;
}
function scenariosView(){return `${heading('Escenarios de práctica','Elige un caso y prepara tu atención.',button(`${icon('upload')} Importar escenario`,'import','secondary'))}<div class="scenario-list">${scenarios().map((s,i)=>`<article class="card"><div class="row between"><span class="badge">CASO ${String(i+1).padStart(2,'0')} · ${e(s.subtitle||'Atención presencial')}</span><span class="small muted">${e(s.difficulty||'Por revisar')}</span></div><h2 style="margin-top:20px">Escenario: ${e(s.publicTitle)} — ${e(s.subtitle||'Atención presencial')}</h2><p class="muted">${e(s.objective)}</p><div class="competencies">${['Bienvenida','Detección de necesidades','Empatía','Inclusión','Recomendación','Documentación','Cierre','Manejo de interrupciones','Postventa'].map(x=>`<span>◇ ${x}</span>`).join('')}</div><div class="meta-grid"><div><small>TIPO</small><strong>${e(s.subtitle||'Atención presencial')}</strong></div><div><small>DURACIÓN</small><strong>${e(s.duration||'Pendiente de revisión')}</strong></div><div><small>DIFICULTAD</small><strong>${e(s.difficulty||'Por revisar')}</strong></div></div><p class="notice">${e(s.context)} Completa el cuestionario para generar tu propuesta.</p><div class="scenario-actions">${button('Comenzar caso →','start','primary',`data-id="${e(s.id)}"`)}${i>0?button('Editar escenario','edit-scenario','secondary',`data-id="${e(s.id)}"`):''}</div></article>`).join('')}</div>`;}
function simulationView(){
 if(state?.questionnaire)return questionnaireView(state,scenario);
 if(!state)return empty('Tu próxima conversación te espera','Selecciona un escenario para comenzar.', '<a class="button" href="#escenarios">Elegir escenario</a>');
 const stages=['welcome','exploration','proposal','questions','closing','postSale'];const idx=stages.indexOf(state.stage);
 const d=state.discovered;const missing=getMissingFields(state,scenario);
 return `${heading('Atención en curso',scenario.publicTitle+' · '+scenario.subtitle,`<div class="small muted">Tiempo de simulación<br><span class="timer" id="timer">${formatDuration((state.endTime||Date.now())-state.startTime)}</span></div>`)}<ol class="phase-list">${['Bienvenida','Exploración','Propuesta','Resolución de dudas','Cierre','Postventa'].map((s,i)=>`<li class="${i===idx?'current':i<idx?'done':''}">${String(i+1).padStart(2,'0')} · ${s}</li>`).join('')}</ol>
 <div class="sim-grid"><div><section class="card chat-card"><div class="chat-header"><div class="row"><span class="avatar">C</span><div><strong>${e(scenario.characters.client||'Cliente presencial')}</strong><p><span class="live-dot"></span>Atención presencial · Caso académico</p></div></div><span class="badge">${state.endTime?'Finalizada':'En conversación'}</span></div><div class="chat-log" id="chat-log" role="log" aria-label="Conversación" aria-live="polite">${state.conversation.length?state.conversation.map(messageHTML).join(''):'<div class="system message"><div class="bubble">El cliente acaba de llegar a la agencia. Recíbelo y comienza la conversación.</div></div>'}</div><form class="composer" id="chat-form"><label for="message">Tu respuesta como asesor</label><div class="compose-row"><textarea id="message" name="message" placeholder="Escribe tu saludo o pregunta al cliente…" required maxlength="2500" ${state.endTime?'disabled':''}></textarea><button class="button primary" type="submit" ${state.endTime?'disabled':''}>Enviar ${icon('send')}</button></div><p class="small muted">Enter para enviar · Mayús + Enter para una nueva línea. Usa solo información ficticia.</p></form><div class="sim-tools">${!state.endTime?`${button('Ver paquetes','packages','secondary')}${state.selectedPackage?button('Reserva simulada','reservation','secondary'):''}${state.reservationCompleted?button('Devolver llamada pendiente','callback','secondary',state.actions.callbackReturned?'disabled':''):''}${settings.demoMode?button('Continuar demostración','demo','secondary'):''}${button('Finalizar y evaluar','finish','secondary')}`:'<a href="#evaluacion" class="button">Ver evaluación</a>'}</div></section>${settings.demoMode&&state.fallbackCount>=2?'<p class="notice">Sugerencia: enfoca la conversación en un tema concreto, como fechas, presupuesto o servicios.</p>':''}${state.selectedPackage?referenceView():''}</div><aside><section class="card capture-card"><div class="row between"><h3 style="margin:0">Datos capturados</h3>${icon('clipboard-list')}</div><p class="small muted" style="margin:5px 0 10px">Solo lo que el cliente ha comunicado.</p><dl class="capture-list">${Object.entries(fieldLabels).map(([k,label])=>`<div><dt>${e(label)}</dt><dd class="${d[k]?.status||'pending'}">${d[k]?.status==='discovered'?'✓ '+e(k==='budget'?'USD '+d[k].value+' / persona':d[k].value):d[k]?.status==='incomplete'?'! Por verificar':'○ Pendiente'}</dd></div>`).join('')}</dl><div class="row between small" style="margin-top:19px"><strong>Avance del caso</strong><span>${state.progress}%</span></div><div class="progress-track"><div class="progress-fill" style="width:${state.progress}%"></div></div></section><section class="card capture-card" style="margin-top:16px"><h3>Preguntas pendientes</h3><ul class="missing">${missing.slice(0,5).map(f=>`<li>Consultar ${e(f.label.toLowerCase())}</li>`).join('')||'<li>Información esencial consultada.</li>'}</ul></section></aside></div>`;
}
function messageHTML(m){return `<div class="message ${e(m.role)}"><small>${e({advisor:'TÚ · ASESOR',client:'CLIENTE',phone:'CLIENTE TELEFÓNICO',system:'SIMULACIÓN'}[m.role]||m.role)}</small><div class="bubble">${e(m.text)}</div></div>`;}
function referenceView(){return `<details class="card doc-reference"><summary>Material de consulta del asesor</summary><p class="notice">Información basada en el guion académico del simulador. No es una consulta migratoria actualizada.</p><ul>${scenario.questions.map(q=>`<li><strong>${e(q.text)}</strong><br>${e(q.answer||'Pendiente de revisión')}</li>`).join('')}</ul><p class="small">${e(scenario.reservationRules.payment||'Condiciones de pago pendientes de revisión.')}</p><p class="small">${e(scenario.reservationRules.cancellation||'Cancelación pendiente de revisión.')}</p><p class="small muted">Consultar este material no asigna puntos. Explica la información al cliente en el chat.</p></details>`;}
function packagesView(){
 if(state?.questionnaire){state.questionnaire.step=3;saveState(state);return questionnaireView(state,scenario);}
 if(!state)return empty('Primero inicia una atención','Las propuestas se adaptan a la información que descubras.','<a href="#escenarios" class="button">Elegir escenario</a>');
 if(!state.discovered.destination&&!settings.demoMode)return empty('Primero conoce el destino','Pregunta al cliente a dónde desea viajar antes de consultar las propuestas.','<a href="#simulacion" class="button">Volver a la conversación</a>');
 const ranked=calculatePackageScores(state,scenario);const top=ranked[0];
 return `${heading('Una propuesta a su medida','Compara las opciones y explica tu recomendación al cliente.','<a class="button secondary" href="#simulacion">← Volver al simulador</a>')}<p class="notice">${state.discovered.budget?'Presupuesto declarado: USD '+e(state.discovered.budget.value)+' por persona.':'Aún no se ha consultado el presupuesto.'} El guion no fija precios por paquete: la compatibilidad económica requiere cotización.</p><div class="packages">${scenario.packages.map(p=>{const r=ranked.find(x=>x.id===p.id);const recommended=top?.id===p.id&&top.score>0;return `<article class="card package ${recommended?'recommended':''}"><span class="badge ${recommended?'':'subtle'}">${recommended?'Recomendado para este cliente':e(p.category||'Categoría por revisar')}</span><h2>${e(p.name)}</h2><p class="small muted">${e(p.category||'Pendiente de revisión')}</p><dl>${[['Vuelos',p.flights],['Alojamiento',p.accommodation],['Alimentación',p.meals],['Traslados',p.transport],['Asistencia',p.assistance]].map(([k,v])=>`<dt>${k}</dt><dd>${e(v||'Pendiente de revisión')}</dd>`).join('')}</dl><h3>Actividades iniciales</h3><ul>${p.initialActivities.map(a=>`<li>${e(a)}</li>`).join('')||'<li>Pendiente de revisión</li>'}</ul>${p.laterTourAnswer.length?`<details class="small"><summary>Respuesta posterior sobre tours</summary><p>${e(p.laterTourAnswer.join(', '))}</p><p class="muted">Se conserva la diferencia del guion.</p></details>`:''}<p class="price">${p.price===null?'Precio no especificado en el guion':'USD '+e(p.price)+' · Valor referencial de simulación'}</p>${r?.reasons.length?`<p class="small">${e(r.reasons.join(' · '))}</p>`:''}${button('Seleccionar propuesta','select-package','primary',`data-id="${e(p.id)}" ${state.endTime?'disabled':''}`)}</article>`;}).join('')||empty('Paquetes pendientes de revisión','Edite el escenario importado para añadir sus propuestas.')}</div>`;
}
function reservationView(){
 const travelerProfile=state?.questionnaire?generateFromForm(scenario,state.questionnaire.data).scenario.hiddenClientProfile:scenario.hiddenClientProfile;
 if(!state?.selectedPackage)return empty('Presenta una propuesta primero','Selecciona y explica un paquete antes de registrar la reserva.','<a href="#simulacion" class="button">Volver al chat</a>');
 if(state.actions.requestedPackage&&state.actions.requestedPackage!==state.selectedPackage)return empty('Confirma la opción elegida por el cliente','El cliente ha solicitado '+(scenario.packages.find(p=>p.id===state.actions.requestedPackage)?.name||'otra propuesta')+'. Selecciona esa propuesta antes de registrar su reserva.','<a href="#paquetes" class="button">Revisar propuestas</a>');
 if(state.reservationCompleted)return `${heading('Reserva registrada','Los datos del formulario no se almacenan.')}<section class="card"><span class="badge">${state.actions.paymentSimulated?'Pago simulado':'Espacios bloqueados · Pago pendiente'}</span><h2 style="margin-top:18px">${e(scenario.packages.find(p=>p.id===state.selectedPackage)?.name)}</h2><p>${e(scenario.reservationRules.payment||'Condiciones pendientes de revisión.')}</p>${button('Simular pago','pay','primary',state.actions.paymentSimulated||state.endTime?'disabled':'')} <a href="#simulacion" class="button secondary">Continuar atención y postventa</a><p class="notice">No se realiza ningún cobro ni reserva real.</p></section>`;
 const total=travelerProfile.travelers?.total||1;
 return `${heading('Reserva y cierre','Registra la reserva con información ficticia.','<a href="#simulacion" class="button secondary">← Volver al simulador</a>')}<form id="reservation-form" class="card"><p class="notice">Utilice información ficticia para esta simulación. Los nombres, documentos, fechas de nacimiento y contactos no se guardan ni se incluyen en reportes.</p><div class="row between" style="margin-bottom:20px"><h2 style="margin:0">${e(scenario.packages.find(p=>p.id===state.selectedPackage)?.name)}</h2>${button('Completar con datos ficticios','fill-fiction','secondary')}</div>${Array.from({length:total},(_,i)=>`<fieldset><legend>Pasajero ${i+1}</legend><div class="traveler-row"><label class="field">Nombres completos<input name="name-${i}" required maxlength="100" autocomplete="off"></label><label class="field">Documento ficticio<input name="document-${i}" required maxlength="30" autocomplete="off"></label><label class="field">Fecha de nacimiento<input name="birth-${i}" type="date" max="${new Date().toISOString().slice(0,10)}" required></label></div></fieldset>`).join('')}<div class="form-grid"><label class="field">Correo ficticio<input type="email" name="email" required autocomplete="off" placeholder="familia@example.com"></label><label class="field">Teléfono ficticio<input name="phone" required maxlength="30" autocomplete="off"></label><label class="field">Forma de pago<select name="payment"><option>Transferencia</option><option>Tarjeta</option><option>Efectivo</option></select></label><label class="field">Observaciones<textarea name="notes" maxlength="500"></textarea></label></div><div class="notice"><strong>Condiciones del escenario académico</strong><p>${e(scenario.reservationRules.payment||'Pago pendiente de revisión.')}</p><p>Plazo para pagar: ${e(scenario.reservationRules.paymentHours?scenario.reservationRules.paymentHours+' horas':'Pendiente de revisión')}.</p><p>${e(scenario.reservationRules.cancellation||'Cancelación pendiente de revisión.')}</p><p>${e(scenario.reservationRules.verification||'Verificación pendiente de revisión.')}</p></div><label class="check-inline"><input type="checkbox" required name="verified">Verifiqué los datos ficticios y entiendo que este registro no procesa una compra.</label><div class="scenario-actions"><button type="submit" class="button primary">Registrar reserva simulada</button></div></form>`;
}
function attachReservation(){document.querySelector('#reservation-form')?.addEventListener('submit',event=>{event.preventDefault();state.reservationCompleted=true;state.actions.travelerDataVerified=true;state.actions.paymentMethod=new FormData(event.target).get('payment');addMessage(state,'system','Reserva simulada registrada. Espacios bloqueados; pago pendiente. Los datos personales del formulario se han descartado.');updateProgress(state);checkAutomaticEvents(state,scenario);saveState(state);showToast('Reserva simulada registrada.','success');navigate('simulacion');});}
function evaluationView(){
 const result=selectedResult|| (state?.endTime?history().find(r=>r.id===state.id):null)||history().at(-1);
 if(!result)return empty('Tu evaluación aparecerá al finalizar','Completa una atención o finalízala para revisar tus competencias.',active()?button('Continuar simulación','resume'):'<a href="#escenarios" class="button">Elegir escenario</a>');
 return `${heading('Tu atención, en perspectiva',result.scenario)}<div class="score-layout"><section class="card score-card"><span class="eyebrow">Resultado general</span><div class="score-ring" style="--score:${result.totalScore}"><div><strong>${result.totalScore}</strong><span>de 100 puntos</span></div></div><h2>${result.kind==='questionnaire'?'Completitud del formulario':scoreLabel(result.totalScore)}</h2><p class="small muted">${e(new Date(result.date).toLocaleString('es-EC'))}<br>Duración: ${e(result.duration)}</p></section><section class="card"><h2>Resultados por área</h2>${Object.entries(result.categories).map(([key,v])=>`<div class="bar-row"><span>${e(result.labels?.[key]||categoryLabels[key])}</span><div class="progress-track" role="meter" aria-label="${e(result.labels?.[key]||categoryLabels[key])}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${v}"><div class="progress-fill" style="width:${v}%"></div></div><strong>${v}%</strong></div>`).join('')}</section></div><div class="feedback-grid"><section class="card"><h2>✓ Fortalezas</h2><ul>${result.strengths.map(x=>`<li>${e(x)}</li>`).join('')||'<li>Aún no hay fortalezas registradas.</li>'}</ul></section><section class="card"><h2>↗ Oportunidades de mejora</h2><ul>${result.improvements.map(x=>`<li>${e(x)}</li>`).join('')||'<li>No se detectaron omisiones en las áreas evaluadas.</li>'}</ul></section></div><section class="card"><h2>Tu próxima práctica</h2><p>${e(result.feedback)}</p><details><summary class="small">Cómo se calculó el puntaje</summary><p class="small">Áreas ponderadas: ${result.rawScore} / 100. Penalizaciones: ${result.deductions.reduce((sum,p)=>sum+p.points,0)}. Puntaje final limitado a 0–100.</p><ul class="small">${result.deductions.map(p=>`<li>${e(p.label)}: ${p.points} puntos</li>`).join('')||'<li>Sin penalizaciones.</li>'}</ul><p class="small">Pendientes: ${e(result.missingFields.join(', ')||'Ninguno de los campos esenciales por consultar.')}</p></details></section><div class="scenario-actions">${button('Reintentar simulación','retry')}${button(`${icon('download')} Descargar reporte`,'download','secondary',`data-id="${e(result.id)}"`)}<a href="#inicio" class="button secondary">Volver al inicio</a></div>`;
}
function resultRows(results){return results.map(r=>`<div class="result-row"><div><strong class="small">${e(r.scenario)}</strong><p>${e(new Date(r.date).toLocaleDateString('es-EC'))} · ${e(r.duration)}</p></div><div class="row"><span class="result-score">${r.totalScore}<small class="small muted"> /100</small></span>${button('Ver resultado','view-result','secondary',`data-id="${e(r.id)}"`)}${button('↓','download','secondary',`data-id="${e(r.id)}" aria-label="Descargar reporte"`)}</div></div>`).join('');}
function reportsView(){const results=history().slice().reverse();return `${heading('Tu historial de aprendizaje','Resultados guardados únicamente en este navegador.')}<section class="card">${results.length?resultRows(results):empty('Aún no hay reportes','Completa tu primera simulación para guardar un resultado.','<a href="#escenarios" class="button">Ver escenarios</a>')}</section>`;}
function settingsView(){return `${heading('Configuración','Prepara el simulador para tu próxima práctica.')}<section class="card"><label class="setting"><div><strong>Modo demostración</strong><p>Permite avanzar al siguiente evento sin completar todas las preguntas. Avanzar no otorga puntos.</p></div><input type="checkbox" id="demo-setting" ${settings.demoMode?'checked':''}></label><label class="setting"><div><strong>Sonido de llamada</strong><p>Un tono breve cuando entra la llamada.</p></div><input type="checkbox" id="sound-setting" ${settings.sound?'checked':''}></label><div class="setting"><div><strong>Reiniciar progreso activo</strong><p>Descarta únicamente la atención en curso. Conserva los reportes y escenarios.</p></div>${button('Reiniciar progreso','reset-active','secondary')}</div><p class="notice">La conversación principal funciona sin Internet. DOCX y PDF cargan sus lectores al importarlos; TXT y JSON funcionan sin conexión.</p></section>`;}
function scrollChat(){const log=document.querySelector('#chat-log');if(log)log.scrollTop=log.scrollHeight;}
function callModal(){
 showModal(`<div class="call-icon">${icon('phone-incoming')}</div><div class="eyebrow">Interrupción de la atención</div><h2 id="modal-title">Llamada entrante</h2><p>Un cliente intenta comunicarse. ¿Qué deseas hacer?</p><div class="call-options">${button('A. Pedir número y devolver llamada','call-choice','secondary','data-id="callback"')}${button('B. Atender la llamada completa','call-choice','secondary','data-id="full"')}${button('C. Rechazar la llamada','call-choice','secondary','data-id="reject"')}</div>`,true);
 if(settings.sound){try{const Audio=window.AudioContext||window.webkitAudioContext;const ctx=new Audio();const osc=ctx.createOscillator();const gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.frequency.value=650;gain.gain.value=.07;osc.start();osc.stop(ctx.currentTime+.3);osc.onended=()=>ctx.close();}catch{/* Sound is optional. */}}
}
function start(id){const selected=scenarios().find(s=>s.id===id)||base;scenario=structuredClone(selected);storage.set('selected_scenario',scenario.id);state=resetSimulation(scenario);state.scenarioSnapshot=structuredClone(scenario);ensureQuestionnaire(state);saveState(state);selectedResult=null;closeModal();if(location.hash==='#simulacion')render('simulacion');else navigate('simulacion');}
function requestStart(id){if(active()&&(state.conversation.length||Object.keys(state.questionnaire?.data||{}).length)){showModal(`<h2 id="modal-title">Comenzar una nueva atención</h2><p>Se descartará el progreso de la atención en curso. Los resultados anteriores se conservarán.</p><div class="scenario-actions">${button('Comenzar nuevo caso','confirmed-start','primary',`data-id="${e(id)}"`)}${button('Cancelar','close','secondary')}</div>`);}else start(id);}
function finish(){
 if(state.endTime){navigate('evaluacion');return;}
 if(!state.incomingCallHandled&&scenario.interruptions.length){state.callPending=true;saveState(state);callModal();return;}
 showModal(`<h2 id="modal-title">Finalizar la atención</h2><p>Se evaluarán las acciones realizadas. Las preguntas y etapas omitidas se reflejarán en el resultado.</p>${state.actions.phoneInterruptionHandledCorrectly&&!state.actions.callbackReturned?'<p class="notice">Tienes una llamada pendiente de devolución.</p>':''}<div class="scenario-actions">${button('Finalizar y ver resultado','confirm-finish')}${button('Seguir practicando','close','secondary')}</div>`);
}
function demoAdvance(){
 if(!settings.demoMode||state.endTime)return;
 if(!state.selectedPackage){navigate('paquetes');return;}
 if(!state.incomingCallHandled&&scenario.interruptions.length){state.callPending=true;saveState(state);callModal();return;}
 if(state.questionIndex<scenario.questions.length-1){nextQuestion(state,scenario);addMessage(state,'system','Avance de demostración: transición sin puntos.');saveState(state);render();return;}
 if(!state.reservationCompleted){navigate('reserva');return;}
 if(!state.actions.demoPostSale){state.actions.demoPostSale=true;addMessage(state,'system','Etapa de postventa: puede ofrecer el seguimiento con sus palabras y luego devolver la llamada.');saveState(state);render();return;}
 if(!state.actions.callbackReturned&&!state.actions.demoCallbackShown){returnCall(state,scenario,false);render();return;}finish();
}
function importModal(){showModal(`<div class="dialog-top"><div><div class="eyebrow">Biblioteca de escenarios</div><h2 id="modal-title">Importar escenario</h2></div>${button('×','close','secondary','aria-label="Cerrar"')}</div><p class="muted small">Carga un guion y revisa la información detectada antes de guardarlo.</p><label class="field">Documento del escenario<input id="scenario-file" type="file" accept=".docx,.pdf,.txt,.json"></label><p class="small muted">DOCX, PDF, TXT o JSON · Máximo 10 MB. PDF con texto seleccionable.</p><div class="notice">El editor muestra datos del caso para su preparación. El estudiante solo los verá al preguntar durante la simulación.</div><p id="import-status" role="status" class="small"></p>`);}
function editorModal(draft){
 importDraft=draft;const s=draft.scenario,p=s.hiddenClientProfile;
 const jsonField=(label,name,value)=>`<label class="field full">${label}<textarea name="${name}" class="editor-json">${e(JSON.stringify(value,null,2))}</textarea></label>`;
 showModal(`<div class="dialog-top"><h2 id="modal-title">Escenario detectado</h2>${button('×','close','secondary','aria-label="Cerrar"')}</div><p class="notice">${e(draft.warnings.join(' '))}</p><form id="editor-form"><div class="form-grid"><label class="field full">Título interno<input name="title" value="${e(s.title)}" required></label><label class="field full">Título público (sin revelar datos ocultos)<input name="publicTitle" value="${e(s.publicTitle)}" required></label><label class="field">Destino<input name="destination" value="${e(p.destination)}" placeholder="Pendiente de revisión"></label><label class="field">Fechas<input name="dates" value="${e(p.dates)}" placeholder="Pendiente de revisión"></label><label class="field">Pasajeros<input name="total" type="number" min="1" max="20" value="${e(p.travelers?.total)}" placeholder="Pendiente de revisión"></label><label class="field">Presupuesto por persona (USD)<input name="budget" type="number" min="0" step="0.01" value="${e(p.budget?.maxPerPerson)}" placeholder="Pendiente de revisión"></label>${jsonField('Personajes (JSON)','characters',s.characters)}${jsonField('Necesidades especiales (JSON)','accessibility',p.accessibility||{})}${jsonField('Mascota (JSON)','pet',p.pet||{})}${jsonField('Paquetes (JSON)','packages',s.packages)}${jsonField('Eventos (JSON)','interruptions',s.interruptions)}<details class="full"><summary>Otros campos del escenario y reglas de evaluación</summary><p class="small muted">Se pueden editar servicios, respuestas, preguntas, condiciones y rúbrica. Los campos visibles de arriba prevalecen.</p>${jsonField('Escenario completo (JSON)','full',s)}</details></div>${draft.rawText?`<details><summary>Texto extraído del documento</summary><pre class="import-source">${e(draft.rawText)}</pre></details>`:''}<p id="editor-error" class="error-text" role="alert"></p><div class="scenario-actions"><button type="submit" class="button primary">Guardar escenario</button>${button('Cancelar','close','secondary')}</div></form>`);
 document.querySelector('#editor-form').addEventListener('submit',event=>{event.preventDefault();const f=new FormData(event.target);try{const s=JSON.parse(f.get('full'));s.id=importDraft.scenario.id;s.title=f.get('title').trim();s.publicTitle=f.get('publicTitle').trim();s.hiddenClientProfile.destination=f.get('destination').trim()||null;s.hiddenClientProfile.dates=f.get('dates').trim()||null;s.hiddenClientProfile.travelers={...s.hiddenClientProfile.travelers,total:f.get('total')?Number(f.get('total')):null};s.hiddenClientProfile.budget={...s.hiddenClientProfile.budget,maxPerPerson:f.get('budget')?Number(f.get('budget')):null};for(const key of ['characters','packages','interruptions'])s[key]=JSON.parse(f.get(key));for(const key of ['accessibility','pet'])s.hiddenClientProfile[key]=JSON.parse(f.get(key));s.metadata={...s.metadata,reviewed:true};const valid=validateScenario(s);const all=storage.get('scenarios',[]).filter(x=>x.id!==valid.id);all.push(valid);if(!storage.set('scenarios',all))throw new Error('No se pudo guardar. El almacenamiento del navegador está lleno o no está disponible.');closeModal();showToast('Escenario guardado. Ya puede comenzar el caso.','success');if(route==='escenarios')render();else navigate('escenarios');}catch(error){document.querySelector('#editor-error').textContent=error.message;}});
}
document.addEventListener('click',event=>{
 const target=event.target.closest('[data-action]');if(!target)return;const action=target.dataset.action,id=target.dataset.id;
 const actions={
 'question-back':()=>{if(state.questionnaire.step>0){state.questionnaire.step--;saveState(state);render();}},
 details:()=>navigate('escenarios'),resume:()=>navigate('simulacion'),start:()=>requestStart(id),'confirmed-start':()=>start(id),close:closeModal,
 packages:()=>navigate('paquetes'),reservation:()=>navigate('reserva'),
 'select-package':()=>{if(!requireState()||state.endTime)return;selectPackage(state,scenario,id);navigate('simulacion');},
 'call-choice':()=>{handleCall(state,id);closeModal();render();},
 callback:()=>{if(state.reservationCompleted&&!state.actions.callbackReturned){returnCall(state,scenario);render();}},
 finish:()=>{if(requireState())finish();},
 'confirm-finish':()=>{state.endTime=Date.now();const result=evaluateSimulation(state,scenario);state.score=result.totalScore;const results=history().filter(r=>r.id!==result.id);results.push(result);storage.set('results',results);saveState(state);selectedResult=result;closeModal();navigate('evaluacion');},
 retry:()=>requestStart(state?.scenarioId||base.id),
 download:()=>{const r=history().find(r=>r.id===id);if(r)downloadReport(r);},
 'view-result':()=>{selectedResult=history().find(r=>r.id===id);navigate('evaluacion');},
 'reset-active':()=>showModal(`<h2 id="modal-title">Reiniciar progreso activo</h2><p>Se descartará la conversación actual. El historial de resultados se conserva.</p><div class="scenario-actions">${button('Reiniciar','confirm-reset')}${button('Cancelar','close','secondary')}</div>`),
 'confirm-reset':()=>{storage.remove('active');state=null;closeModal();showToast('Progreso activo reiniciado.','success');render();},
 'fill-fiction':()=>{const form=document.querySelector('#reservation-form');const total=state.questionnaire?Number(state.questionnaire.data.adults||0)+Number(state.questionnaire.data.children||0):scenario.hiddenClientProfile.travelers?.total||1;for(let i=0;i<total;i++){form.elements[`name-${i}`].value=`Viajero Demostración ${i+1}`;form.elements[`document-${i}`].value=`DEMO-00${i+1}`;form.elements[`birth-${i}`].value=i<2?'1988-04-12':'2016-03-10';}form.elements.email.value='familia@example.com';form.elements.phone.value='DEMO-TELEFONO';},
 pay:()=>{if(!state.endTime){state.actions.paymentSimulated=true;saveState(state);showToast('Pago simulado. No se realizó ningún cobro.','success');render();}},demo:demoAdvance,import:importModal,
 'edit-scenario':()=>{const s=scenarios().find(s=>s.id===id);editorModal({scenario:structuredClone(s),rawText:'',warnings:['Edición del escenario para futuras simulaciones.']});}
 };actions[action]?.();
});
function readQuestionnaire(form){
 const values={};
 for(const field of form.elements){if(!field.name||field.name==='package')continue;values[field.name]=field.type==='checkbox'?field.checked:field.value;}
 storeFormStep(state,values);
 state.discovered=generateFromForm(scenario,state.questionnaire.data).discovered;
 saveState(state);
}
document.addEventListener('input',event=>{
 const form=event.target.closest('#questionnaire-form');if(!form||state?.endTime)return;
 readQuestionnaire(form);
 if(event.target.name==='package'){selectFormPackage(state,scenario,event.target.value);saveState(state);}
 for(const fieldset of form.querySelectorAll('[data-conditional]'))fieldset.hidden=state.questionnaire.data[fieldset.dataset.conditional]!=='yes';
 const preview=document.createElement('template');preview.innerHTML=questionnaireView(state,scenario);
 document.querySelector('.question-summary').innerHTML=preview.content.querySelector('.question-summary').innerHTML;
});
document.addEventListener('submit',event=>{
 if(event.target.id==='questionnaire-form'){
   event.preventDefault();if(!state||state.endTime)return;readQuestionnaire(event.target);
   const q=state.questionnaire,error=validateStep(q.step,q.data);
   if(error){document.querySelector('#questionnaire-error').textContent=error;return;}
   if(q.step===3){const output=generateFromForm(scenario,q.data);const selected=new FormData(event.target).get('package');
     if(output.ranked.length&&!output.ranked.some(p=>p.id===selected)){document.querySelector('#questionnaire-error').textContent='Selecciona una propuesta para continuar.';return;}
     state.selectedPackage=selected||null;
     if(selected&&!state.incomingCallHandled&&scenario.interruptions.length)state.callPending=true;
   }
   if(!q.completed.includes(q.step))q.completed.push(q.step);
   if(q.step<4)q.step++;else {state.followUpCompleted=['email','whatsapp','advice','future'].some(k=>q.data[k]);showToast('Plan de seguimiento guardado.','success');}
   state.progress=Math.round(q.completed.length/5*100);saveState(state);render();window.scrollTo({top:0});return;
 }
 if(event.target.id!=='chat-form')return;event.preventDefault();if(!state||state.endTime)return;const input=document.querySelector('#message');const message=input.value.trim();if(!message)return;processAdvisorMessage(state,scenario,message);render();document.querySelector('#message')?.focus();
});
document.addEventListener('keydown',event=>{if(event.target.id==='message'&&event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();document.querySelector('#chat-form').requestSubmit();}});
document.addEventListener('change',async event=>{
 if(event.target.id==='demo-setting'||event.target.id==='sound-setting'){settings[event.target.id==='demo-setting'?'demoMode':'sound']=event.target.checked;storage.set('settings',settings);render();}
 if(event.target.id==='scenario-file'&&event.target.files[0]){const file=event.target.files[0];const status=document.querySelector('#import-status');status.textContent='Extrayendo texto…';event.target.disabled=true;try{const draft=await importScenario(file,base);editorModal(draft);}catch(error){status.textContent='No fue posible importar el archivo. '+error.message;status.className='error-text';event.target.disabled=false;}}
});
document.querySelector('#menu-toggle').addEventListener('click',()=>{const sidebar=document.querySelector('#sidebar');const open=sidebar.classList.toggle('open');sidebar.inert=!open&&matchMedia('(max-width:850px)').matches;document.querySelector('#menu-toggle').setAttribute('aria-expanded',String(open));});
matchMedia('(max-width:850px)').addEventListener('change',event=>{const sidebar=document.querySelector('#sidebar');sidebar.inert=event.matches&&!sidebar.classList.contains('open');});
document.querySelector('.skip').addEventListener('click',event=>{event.preventDefault();main.focus();});
window.addEventListener('storage-warning',()=>showToast('No se pudo guardar en este navegador. La sesión continúa en memoria.','warning'));
setInterval(()=>{const timer=document.querySelector('#timer');if(timer&&state)timer.textContent=formatDuration((state.endTime||Date.now())-state.startTime);},1000);
async function boot(){
 try{base=await loadDefaultScenario();state=storage.get('active');scenario=state?.scenarioSnapshot||scenarios().find(s=>s.id===state?.scenarioId)||base;
 if(state){try{scenario=validateScenario(scenario);if(state.scenarioId!==scenario.id||!state.metrics||!Array.isArray(state.conversation)||!Array.isArray(state.answeredQuestions))throw new Error();}catch{state=null;storage.remove('active');showToast('No fue posible cargar el escenario. Se utilizará el escenario predeterminado.','warning');}}
 setupRouter(render);
 // Icons are decorative; offline operation never depends on this CDN.
 loadScript('https://cdn.jsdelivr.net/npm/lucide@0.468.0/dist/umd/lucide.min.js').then(refreshIcons).catch(()=>{});
 fetch('data/source-fingerprint.txt').then(r=>r.ok?r.text():'').then(text=>{if(text)storage.set('source_fingerprint',text.trim());}).catch(()=>{});
 }catch(error){main.innerHTML=empty('No fue posible cargar el escenario','Abra el proyecto con Live Server o un servidor local y compruebe que data/default-scenario.json esté disponible.',button('Reintentar','reload','secondary'));document.querySelector('[data-action="reload"]')?.addEventListener('click',boot);}}
boot();
