import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {ensureQuestionnaire,generateFromForm,validateStep,storeFormStep,selectFormPackage,questionnaireView} from '../js/questionnaire.js';
import {createState} from '../js/simulator.js';
import {evaluateSimulation} from '../js/evaluator.js';
const source=JSON.parse(fs.readFileSync(new URL('../data/default-scenario.json',import.meta.url)));
const full={tripType:'Internacional',destination:'Panamá',start:'2027-08-05',end:'2027-08-12',adults:'2',children:'1',purpose:'Turismo',budget:'1500',service0:true,service1:true,service2:true,service3:true,meals:'full',transport:'private',priority:'comfort',special:'yes',condition:'Autismo',supervision:'Con sus padres',sensory:'Ruidos fuertes',pet:'yes',species:'Perro',petSize:'Por verificar',petWeight:'Por verificar',email:true,whatsapp:true,advice:true,future:true};
function state(){const st=createState(source);ensureQuestionnaire(st);st.questionnaire.data={...full};return st;}
test('Formulario vacío no hereda datos ocultos ni propuestas',()=>{const out=generateFromForm(source,{});assert.deepEqual(out.discovered,{});assert.equal(out.ranked.length,0);assert.equal(out.scenario.hiddenClientProfile.destination,null);});
test('Respuestas generan perfil y propuestas sin modificar fuente',()=>{const before=JSON.stringify(source);const out=generateFromForm(source,full);assert.equal(out.scenario.hiddenClientProfile.travelers.total,3);assert.equal(out.ranked[0].id,'relax');assert.equal(JSON.stringify(source),before);});
test('Preferencias distintas cambian la recomendación',()=>{const out=generateFromForm(source,{...full,budget:'800',special:'no',pet:'no',priority:'quiet',meals:'breakfast',transport:'standard'});assert.equal(out.ranked[0].id,'explora');assert(!out.discovered.accessibility);assert(!out.discovered.sensory);});
test('Destino distinto no genera ofertas ni requisitos de Panamá',()=>{const out=generateFromForm(source,{...full,destination:'Cuenca'});assert.equal(out.ranked.length,0);assert.equal(out.scenario.questions.length,0);assert.deepEqual(out.scenario.reservationRules,{});});
test('Valida fechas, viajeros, presupuesto y campos condicionales',()=>{assert(validateStep(0,{...full,end:'2027-08-01'}));assert(validateStep(0,{...full,children:''}));assert(validateStep(0,{...full,adults:'21'}));assert(validateStep(1,{...full,budget:'-1'}));assert(validateStep(2,{...full,condition:''}));assert.equal(validateStep(2,{...full,special:'no',pet:'no',condition:'',species:''}),null);});
test('Editar perfil invalida reserva y propuesta anteriores',()=>{const st=state();st.selectedPackage='relax';st.reservationCompleted=true;st.questionnaire.step=0;st.questionnaire.completed=[0,1,2,3,4];storeFormStep(st,{destination:'Cuenca'});assert.equal(st.selectedPackage,null);assert.equal(st.reservationCompleted,false);assert.deepEqual(st.questionnaire.completed,[0]);});
test('Cambiar propuesta invalida pago y reserva',()=>{const st=state();st.selectedPackage='relax';st.reservationCompleted=true;st.actions.paymentSimulated=true;assert(selectFormPackage(st,source,'explora'));assert.equal(st.reservationCompleted,false);assert.equal(st.actions.paymentSimulated,false);assert(!selectFormPackage(st,source,'no-existe'));});
test('Calificación del formulario no atribuye competencias conversacionales',()=>{const st=state();st.selectedPackage='relax';st.reservationCompleted=true;const r=evaluateSimulation(st,source);assert.equal(r.kind,'questionnaire');assert.equal(r.totalScore,100);assert(!('greeting' in r.categories));assert(!st.metrics.greeting);});
test('Recarga conserva respuestas y campos condicionales',()=>{const st=JSON.parse(JSON.stringify(state()));st.questionnaire.step=2;const html=questionnaireView(st,source);assert(html.includes('value="Perro"'));assert(html.includes('data-conditional="special" >'));assert(!html.includes('id="chat-form"'));});
